# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('speciality', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('fax', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('schedule', models.TextField()),
                ('photo', models.ImageField(upload_to=None)),
                ('site', models.URLField()),
            ],
        ),
    ]
