# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20160119_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fax',
            field=models.CharField(default=' ', max_length=14),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='site',
            field=models.URLField(default=' '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.TextField(default=' '),
        ),
    ]
