# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20160119_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=' ', max_length=14),
        ),
    ]
