# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20160119_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='site',
        ),
    ]
