# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20160119_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.TextField(default='médecine générale'),
        ),
    ]
