# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20160119_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.TextField(default='Du lundi au vendredi de 9h à 17h'),
        ),
    ]
