# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20160119_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(default='77420 Champs-sur-Marne'),
        ),
    ]
