# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_auto_20160119_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
    ]
