# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_remove_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nb_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='travel_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='waiting_time',
            field=models.FloatField(default=0),
        ),
    ]
