# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20160202_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
