# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='waiting_time',
            field=models.DurationField(default=0),
        ),
    ]
