# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.TextField(default='Champs-sur-Marne'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_street',
            field=models.TextField(default='Ampère'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='num_street',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='type_street',
            field=models.TextField(default='rue'),
        ),
    ]
