# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_auto_20160205_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor'),
        ),
    ]
