# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_auto_20160205_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
