# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0025_patient_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='waiting_time',
            new_name='waiting_room',
        ),
    ]
