# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_auto_20160205_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='waiting_room',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
